In [6]:
import pandas as pd

orders_data = [
    [101, "John", "Laptop", 2, 120000, "Chennai", "2026-06-10", "2026-06-12", "Delivered"],
    [102, "Mary", "Mobile", 1, 30000, "Coimbatore", "2026-06-11", "2026-06-15", "Pending"],
    [103, "David", "Tablet", 3, 75000, "Madurai", "2026-06-12", "2026-06-14", "Shipped"],
    [104, "Sarah", "Monitor", 2, 40000, "Salem", "2026-06-13", "2026-06-18", "Delivered"],
    [105, "James", "Keyboard", 5, 10000, "Trichy", "2026-06-14", "2026-06-14", "Pending"],
    [106, "Priya", "Headphones", 4, 20000, "Erode", "2026-06-15", "2026-06-20", "Shipped"],
    [107, "Arun", "Laptop", 1, 60000, "Chennai", "2026-06-16", "2026-06-25", "Pending"],
    [108, "Anita", "Mobile", 2, 50000, "Coimbatore", "2026-06-17", "2026-06-19", "Delivered"],
    [109, "Rahul", "Tablet", 1, 25000, "Madurai", "2026-06-18", "2026-06-24", "Pending"],
    [110, "Sneha", "Monitor", 3, 60000, "Salem", "2026-06-19", "2026-06-21", "Delivered"]
]

columns = [
    "order_id",
    "customer_name",
    "product",
    "quantity",
    "order_amount",
    "city",
    "expected_date",
    "actual_date",
    "delivery_status"
]

orders_df = pd.DataFrame(orders_data, columns=columns)

display(orders_df)

,order_id,customer_name,product,quantity,order_amount,city,expected_date,actual_date,delivery_status
0,101,John,Laptop,2,120000,Chennai,2026-06-10,2026-06-12,Delivered
1,102,Mary,Mobile,1,30000,Coimbatore,2026-06-11,2026-06-15,Pending
2,103,David,Tablet,3,75000,Madurai,2026-06-12,2026-06-14,Shipped
3,104,Sarah,Monitor,2,40000,Salem,2026-06-13,2026-06-18,Delivered
4,105,James,Keyboard,5,10000,Trichy,2026-06-14,2026-06-14,Pending
5,106,Priya,Headphones,4,20000,Erode,2026-06-15,2026-06-20,Shipped
6,107,Arun,Laptop,1,60000,Chennai,2026-06-16,2026-06-25,Pending
7,108,Anita,Mobile,2,50000,Coimbatore,2026-06-17,2026-06-19,Delivered
8,109,Rahul,Tablet,1,25000,Madurai,2026-06-18,2026-06-24,Pending
9,110,Sneha,Monitor,3,60000,Salem,2026-06-19,2026-06-21,Delivered

In [2]:
orders_df.to_csv("cleaned_orders.csv", index=False)

print("CSV file created successfully.")

CSV file created successfully.

In [3]:
from google.colab import files

files.download("cleaned_orders.csv")

In [4]:
df = pd.read_csv("cleaned_orders.csv")

print("Loaded Dataset")
df.head()

Loaded Dataset

,order_id,customer_name,product,quantity,order_amount,city,expected_date,actual_date,delivery_status
0,101,John,Laptop,2,120000,Chennai,2026-06-10,2026-06-12,Delivered
1,102,Mary,Mobile,1,30000,Coimbatore,2026-06-11,2026-06-15,Pending
2,103,David,Tablet,3,75000,Madurai,2026-06-12,2026-06-14,Shipped
3,104,Sarah,Monitor,2,40000,Salem,2026-06-13,2026-06-18,Delivered
4,105,James,Keyboard,5,10000,Trichy,2026-06-14,2026-06-14,Pending

In [10]:
df.loc[
    (df["expected_date"] <= df["actual_date"]) &
    (df["delivery_status"] == "Pending"),
    "delivery_status"
] = "Delivered"

print("Updated Delivery Status")
df.head()

Updated Delivery Status

,order_id,customer_name,product,quantity,order_amount,city,expected_date,actual_date,delivery_status,delay_days
0,101,John,Laptop,2,120000,Chennai,2026-06-10,2026-06-12,Delivered,2
1,102,Mary,Mobile,1,30000,Coimbatore,2026-06-11,2026-06-15,Delivered,4
2,103,David,Tablet,3,75000,Madurai,2026-06-12,2026-06-14,Shipped,2
3,104,Sarah,Monitor,2,40000,Salem,2026-06-13,2026-06-18,Delivered,5
4,105,James,Keyboard,5,10000,Trichy,2026-06-14,2026-06-14,Delivered,0

In [11]:
df["expected_date"] = pd.to_datetime(df["expected_date"])
df["actual_date"] = pd.to_datetime(df["actual_date"])

df["delay_days"] = (
    df["actual_date"] - df["expected_date"]
).dt.days

df.head()

,order_id,customer_name,product,quantity,order_amount,city,expected_date,actual_date,delivery_status,delay_days
0,101,John,Laptop,2,120000,Chennai,2026-06-10,2026-06-12,Delivered,2
1,102,Mary,Mobile,1,30000,Coimbatore,2026-06-11,2026-06-15,Delivered,4
2,103,David,Tablet,3,75000,Madurai,2026-06-12,2026-06-14,Shipped,2
3,104,Sarah,Monitor,2,40000,Salem,2026-06-13,2026-06-18,Delivered,5
4,105,James,Keyboard,5,10000,Trichy,2026-06-14,2026-06-14,Delivered,0

In [12]:
df["is_delayed"] = df["delay_days"].apply(
    lambda x: "Yes" if x > 0 else "No"
)

df.head()

,order_id,customer_name,product,quantity,order_amount,city,expected_date,actual_date,delivery_status,delay_days,is_delayed
0,101,John,Laptop,2,120000,Chennai,2026-06-10,2026-06-12,Delivered,2,Yes
1,102,Mary,Mobile,1,30000,Coimbatore,2026-06-11,2026-06-15,Delivered,4,Yes
2,103,David,Tablet,3,75000,Madurai,2026-06-12,2026-06-14,Shipped,2,Yes
3,104,Sarah,Monitor,2,40000,Salem,2026-06-13,2026-06-18,Delivered,5,Yes
4,105,James,Keyboard,5,10000,Trichy,2026-06-14,2026-06-14,Delivered,0,No

In [13]:
df.to_csv("final_orders_output.csv", index=False)

print("Final Output Saved")

Final Output Saved

In [14]:
from google.colab import files

files.download("final_orders_output.csv")

In [15]:
!pip install deltalake

Collecting deltalake
  Downloading deltalake-1.6.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Collecting arro3-core>=0.5.0 (from deltalake)
  Downloading arro3_core-0.8.1-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (515 bytes)
Collecting deprecated>=1.2.18 (from deltalake)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated>=1.2.18->deltalake) (2.2.1)
Downloading deltalake-1.6.1-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 MB 20.1 MB/s eta 0:00:00
Downloading arro3_core-0.8.1-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 75.2 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: deprecated, arro3-core, deltalake
Successfully installed arro3-core-0.8.1 deltalake-1.6.1 deprecated-1.3.1

In [16]:
from deltalake.writer import write_deltalake

write_deltalake(
    "orders_delta_table",
    df
)

print("Delta Table Created")

Delta Table Created

In [17]:
!zip -r orders_delta_table.zip orders_delta_table
files.download("orders_delta_table.zip")

  adding: orders_delta_table/ (stored 0%)
  adding: orders_delta_table/_delta_log/ (stored 0%)
  adding: orders_delta_table/_delta_log/00000000000000000000.json (deflated 66%)
  adding: orders_delta_table/part-00000-6c516f81-f3d2-4c9d-8fb5-cd6eee8f5d2b-c000.snappy.parquet (deflated 54%)

In [18]:
top5 = (df.sort_values(
            by="delay_days",
            ascending=False)
          [["customer_name", "delay_days"]]
          .head(5))

print("Top 5 Delayed Customers")
print(top5)

Top 5 Delayed Customers
  customer_name  delay_days
6          Arun           9
8         Rahul           6
3         Sarah           5
5         Priya           5
1          Mary           4